### ISSUE TITLE
Need a good workable way to experiment with weight deviation penalties

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#100]
As noted in #99, our weight changes are worrying in the current setup, which by default imposes no penalty on changes in weights. It is extremely important to consider penalties on changes in weights.

The function reweight in reweight.py does have an argument, `weight_deviation_penalty`, with a default value of zero, that determines the extent to which the calculated weight-change penalty (sum of absolute changes in weights / sum of original weights) is considered in the loss function.

I have been trying to experiment with the weight_deviation_penalty parameter. It is not a parameter that can be set at runtime, but rather is hard-coded in the call to reweight on line 41 in tmd.py:

`combined = reweight(combined, 2021, weight_deviation_penalty=0.0)`

However, I am not sure how to do this properly. I have tried the following:

- create a separate branch for each penalty value -- for wpenalty.01 for a value of 0.1
- checkout the branch
- make the change to line 41
- save and commit
- execute `make flat-file` in the terminal

The first time I did it, it worked for a value of 0.1. Since then it has not worked. When I set it to 0.5 I found that it was generating errors when imputing the pass-through for W-2 wages -- it was not satisfying the 1e-2 tolerance -- see 1st and 2nd screenshots below.

I wondered whether it was reading an old file and if that was the problem. However, when I deleted all files in the output folder and reran it, I got the same error.

I suspect I may be doing something wrong. In any event, it is important for us to have a simple parameterized way to investigate how a weight-change penalty affects results, without having to hard-code changes, so I think it would be good to set that up.

Advice / thoughts, @nikhilwoodruff and @martinholmer?

**1st screenshot**

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/b80be88f-1af9-4da6-b0c2-de1902ec3379)

**2nd screenshot**

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/9ce48437-3795-44e1-bb49-6aad780d1573)

**Comment by nikhilwoodruff** [comment]
OK- I'll add a top-level parameter for this. Do you think we should relax the PT W2 wage scale test limit?

**Comment by donboyd5** [comment]
@martinholmer FYI

Thank you. I don't know. I need a little bit of education on the code above. If we believe that the result of the bisect search MUST result in pt_w2_wages_scale being equal to INITIAL_W2_WAGES_SCALE within a small tolerance, and we're going to reject anything that doesn't satisfy that, why do we even bother with the search? I thought the whole purpose of the search was to find a scaling factor that makes our calculated qbided equal to $205.8 billion; I didn't appreciate that we also thought the scaling factor we're looking for always has to equal 0.19824 (or any other specific number), within a small tolerance.

And this seems (to me) inconsistent with what we're doing. If pt_w2_wages_scale depends in part on the particular set of weights we choose (it is done after reweighting optimization), then why do we expect it to equal a specific value?

So I would like to understand better why we ever imposed this requirement. I must not have paid close enough attention when we discussed it in a phone call. And I didn't find any documentation explaining why we require this. I also have another question or two about how we're implementing the search for a qbi scaling factor. So I'd like to discuss it in our next call.

**Comment by donboyd5** [comment]
As we've discussed, I think we should remove the `raise ValueError(msg)` and simply display the msg. It is expected and acceptable for the scaling factor to change when we change weights so we shouldn't stop the data-creation process when it changes. However, we want to see how much it has changed as very large changes could suggest there is some other problem (but might not suggest that, so we won't stop on that basis).

I'll leave this open for a short while then close it.

**Comment by martinholmer** [comment]
@donboyd5 said in issue #100:
> As we've discussed, I think we should remove the `raise ValueError(msg)` and simply display the `msg`. It is expected **and acceptable** for the scaling factor to change when we change weights so we shouldn't stop the data-creation process when it changes.

I do not agree with this notion that using inconsistent W-2 wages scaling parameter values at different stages of the data-creation process leads to an "acceptable" TMD dataset.

**Comment by donboyd5** [comment]
You are right, @martinholmer, we should not allow inconsistent scaling parameters. The only reason for an initial (i.e., to-be-used-for-2015) scaling parameter -- and the source of the inconsistency -- is that we use it to create PT_binc_w2_wages and qbided in 2015. The only value I can think of for having those variables in 2015 is to answer the question, "what would have happened if the TCJA had been put into effect in 2015?"

At present, to provide those 2015 variables we engage in circularity: We need 2015 PT_binc_w2_wages to calculate 2015 qbided, which in turn requires a 2015 scaling factor. There are no 2015 qbided data to calibrate against to determine that 2015 scaling factor because TCJA had not yet been passed. So we use a 2021 scaling factor we previously created to construct 2015 PT_binc_w2_wages and qbided. It was a reasonable approach, if we really needed 2015 T_binc_w2_wages and qbided.

We do not use the 2015 values in any way to construct 2021 PT_binc_w2_wages and qbided. Instead and properly, we use the grown components of qbi (qbinc in Tax-Calculator naming):  e00900 + e26270 + e02100 + e27200. After we construct final 2021 weights we calculate a 2021 scaling factor for real so that we can construct 2021 PT_binc_w2_wages, and ultimately 2021 qbided, with qbided calibrated to the known (IRS-published) 2021 qbid value. This calibrated scaling factor is the one we most want to be correct and there's no reason for us to reject it because it is (slightly) inconsistent with a previously constructed 2021 scaling factor that was only used to create 2015 PT_binc_w2_wages and qbided, which in turn are only useful for answering a question that may not even get asked. The solution is not to reject a scaling factor that is well constructed thanks to your idea, and relevant, simply because it differs from a less-well-constructed scaling factor that as far as we can tell is irrelevant.

That leaves us with (at least) a few possible solutions:

1. Simply remove PT_binc_w2_wages and qbided from 2015, and worry about it later in the project; we should verify with @nikhilwoodruff to make sure there would not be any side effects, but I don't think there would be (unless someone asks the TCJA-in-2015 question). We could keep this issue or a new issue open until we come back and do that.
2. Replace them with values estimated on a different basis - for example, we could estimate (guess at) a 2015 qbided value, perhaps by walking the IRS-published 2021 $205.8 billion qbided value backwards by 6 years using some simple method and then using our search method to find the scaling factor consistent with that backcasted qbided target. (This might lead to a scaling factor no better or worse than the one we have now, but not so obviously inconsistent.)
3. After the 2021 tmd file is constructed, use the well-constructed 2021 scaling factor (the one we have now but currently gets rejected if it disagrees with the less-well-constructed factor used for 2015) to construct PT_binc_w2_wages and qbided for 2015 (using the unsupported but perhaps better-than-any-other assumption that the relationship between PT_binc_w2_wages and qbi would have been the same in 2015 as in 2021).

Given how much we have to do, I favor the first approach.
