### ISSUE TITLE
Fixes branch fails, cannot hit qbided target

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#113]
@nikhilwoodruff @martinholmer 

I just ran make data with the latest commit to the fixes branch:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/9a2c3fdd-b11a-495c-86eb-69a86fc1838a)

Unfortunately it fails at the point it tries to solve for a scaling factor that hits the qbided target.

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/5710a79d-d0c7-4fb6-8227-1f027ecf0f4c)

I ran into this once before on a recent effort to make data with fixes. As you can see, it comes up with an initial value for qbided of $106.596 which is not at all close to the target of $205.8. Even with a scale value of 0.9 -- which says that 90% of qb income is wages, so it's much higher than we would think is plausible, we can only attain qbided of $204.141; we can't solve the problem by increasing the range for the scaling factor.

This requires a careful look at how qbi and qbided are being calculated - how is it possible that it was so easy before to hit our qbided target with a scaling factor of about 0.20 -- only 20% of qbi was pass-through wages, and now we can't hit it when we assume it is 90% of wages. 

That's odd. Is it the result of reweighting? One thing you could do, @nikhilwoodruff, is print qbi out (as well as qbided and pass-through wages, which currently are printed out) before reweighting and right after reweighting, before anything else, to see what reweighting has done to it. Seems like this should be a simple change to the trace1 function.

Also, perhaps you should walk us through this with debugging tomorrow.

**Comment by nikhilwoodruff** [comment]
Was just about to comment actually, I'm not sure on the QBI deduction. The good news is I've got the reweighing algorithm targeting AGI+wages distributions and aggregates for everything else, which is almost certainly the cause of this (it feels like it's something to do with the fact that we hit the QBI target before this optimisation?).

**Comment by nikhilwoodruff** [comment]
The fact that a scale factor of 1 is dead on the target QBI feels like a hint here though

**Comment by donboyd5** [comment]
Thanks.

**Comment by donboyd5** [comment]
FWIW, I had assumed you would simply:

- run scaling-factor-seeking algorithm before reweighting, and use W2 wages and qbided from that (which would be 205.8), and then simply target qbided in reweighting (without doing a 2nd search for a scaling factor)

That might be just fine. I haven't given it a lot of thought.

**Comment by donboyd5** [comment]
@nikhilwoodruff @martinholmer 

Fixes branch still failing after commit fa461e0:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/44cb14c7-794d-4b9a-9103-097b6d53c1e9)


![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/99f38ec3-e18a-44cd-b486-709a630c26d0)
