### ISSUE TITLE
Testing weight-deviation penalty when we reweight

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#114]
@nikhilwoodruff, FYI @martinholmer 

Reminder that we'll want to start imposing a weight-deviation penalty in the reweighting algorithm. My last successful run of make data, using current master, has this for s006 and s006_original -- largest weight before reweighting was 9675 and after reweighting largest was 70664, which is dramatic and I think we want to prevent it. I know we've got tighter bounds about to be implemented on weight ratios, which will probably solve the problem so we can discuss impact of that first. Simply opening this issue to make sure we put some effort into analyzing and addressing this as we think best.

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/ff7165ff-ec4d-4a7a-abff-c0b749cf4a46)

**Comment by martinholmer** [comment]
@donboyd5,  Given the results of PR #148, there seems to be less reason to experiment with a positive value of the REWEIGHT_DEVIATION_PENALTY.   But, after PR #148 is merged, it would be interesting to do this experiment: use the master branch and make one change (changing the PENALTY value from 0.0 to 0.2) and use the method illustrated in issue #146 to see how the 2023 tax expenditure estimates change when imposing the penalty.

**Comment by donboyd5** [comment]
Currently @martinholmer does not have time to apply the L-BFGS-B method with weight-deviation penalty (regularization), as is done for areas, to the national TMD data. If time becomes available and we apply L-BFGS-B method to national data, that will resolve this issue.
