### ISSUE TITLE
QBI deduction and reweighting

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#115]
We can't let the QBI deduction drive reweighting. I thought we'd been told that qbided enters into the calculation of AGI, which is the reason we needed it before reweighting - so that we can target AGI in total and by AGI range, and so that we can target other variables by AGI range. However, ChatGPT (never to be trusted 100%) says qbided does **not** enter into the calculation of AGI (although it does enter into taxable income and tax). Here's a partial ChatGPT response to the question, "does the qualified business income deduction enter into the calculation of agi":

`No, the Qualified Business Income Deduction (QBID), also known as the Section 199A deduction, does not enter into the calculation of Adjusted Gross Income (AGI). Instead, it is taken below the line, which means it is deducted from AGI to determine taxable income.`

Details available by asking the same question.

@nikhilwoodruff, can  you please verify this by using Tax-Calculator to calculate AGI with some reasonable qbided estimate and with no qbided?

If qbided **does** (counter to expectations) affect AGI, please let us know, and by how much, and what seems to cause it.

**Assuming qbided indeed does NOT affect AGI**, then let's proceed as follows:

- Combine puf, and cps nonfilers, as now
- Run through Tax-Calculator to get AGI, which we need for targeting; tax calculations will be junk because there's no qbi deduction yet, but we just need AGI at this point 
- Reweight, as now, targeting the main components of QBI (qualified business income, not the QBI deduction) along with all the other things you're targeting (which I think already gets the QBI items). **Important not to target tax items, because qbided will affect them and at this point qbided is zero.**
- Estimate pt_w2_wages_scale, PT_binc_w2_wages, and qbided using the current bisect method but with much broader bounds for scale - perhaps [0.0, 10.0] (at some point please look at my comment on one of your commits about using interpolation, which will be faster than a binary search for the scaling factor) [If I understand the calculation properly, an upper bound of 10.0 should be no different from an upper bound of 1.0, but let's see. If raising the upper bound has no meaningful impact on qbided, this would seem to be mild support for our shared hypothesis that qbided can't be well approximated by a simple linear relationship. But in any event, let's not let qbided drive reweighting. We do want it to be correct, but we don't want to make a lot of other things wrong in the process.]
- This process returns a tc-enhanced file that should (right?) have the same AGI as the file we sent into it, but will now have more appropriate tax calculations because it will have used W2 wages and qbided
- Use the resulting file as our tc-enhanced tmd file
 
Does this make sense?

**Comment by MaxGhenis** [comment]
FWIW Claude 3.5 Sonnet agreed:

> The Qualified Business Income (QBI) deduction does not enter into the calculation of Adjusted Gross Income (AGI). Here's a brief explanation:
> 
> 1. AGI calculation: AGI is calculated by taking your total income and subtracting specific adjustments, such as student loan interest, alimony payments, or contributions to a traditional IRA.
> 
> 2. QBI deduction timing: The QBI deduction is taken after AGI has been calculated. It's considered a "below-the-line" deduction, which means it's applied after your AGI has been determined.
> 
> 3. Tax form placement: On Form 1040, the QBI deduction appears on line 13, which is after the AGI calculation on line 11.
> 
> The QBI deduction reduces your taxable income, but not your AGI. This distinction can be important because many tax benefits and limitations are based on your AGI.
> 
> Would you like me to elaborate on any aspect of this or explain how the QBI deduction affects your overall tax calculation?


Here's the relevant part of the [1040](https://www.irs.gov/pub/irs-pdf/f1040.pdf) corroborating this:
<img width="752" alt="image" src="https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6076111/0c593701-5474-4220-935a-e5233fe3ef7f">
<img width="752" alt="image" src="https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6076111/0c593701-5474-4220-935a-e5233fe3ef7f">

**Comment by donboyd5** [comment]
Thanks, @MaxGhenis!

**Comment by nikhilwoodruff** [comment]
@donboyd5 verified on the AGI question.

**Comment by martinholmer** [comment]
After the merge of PR #124, we are simply using the assumed value of `W2_WAGES_SCALE` (which is located in the `imputation_assumptions.py` module) to impute values for the pass-through business W-2 wages variable very early in the `tmd.csv` file creation process:

https://github.com/PSLmodels/tax-microdata-benchmarking/blob/eab7d999ff021b007025eaa103757256132da381/tax_microdata_benchmarking/datasets/puf.py#L183-L187

This approach yields a good QBID tax-expenditure estimate as seen in [examination/results3.md](https://github.com/PSLmodels/tax-microdata-benchmarking/blob/master/tax_microdata_benchmarking/examination/results3.md).

Now that we all are in agreement that the QBI deduction does not affect AGI, it seems as if this issue can be closed.
