### ISSUE TITLE
Fix tax-expenditure tests in the tests folder

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/tax-microdata-benchmarking#116]
In our team call earlier today, @nikhilwoodruff asked @martinholmer to look at the tax-expenditure tests code (**not** the logic in the `examination` folder).  After reviewing the `tests/test_flat_file.py` code, I found that the code did not advance the Tax-Calculator `Calculator` object from 2021 (the year of the TMD input data) to 2023 (the year for which the tax-expenditure tests are conducted).

I will offer a pull request that fixes this problem soon.   I will leave it open for the team to review.

**Comment by nikhilwoodruff** [comment]
Thanks Martin!
