### ISSUE TITLE
Getting the SALT deduction right

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#126]
@nikhilwoodruff @martinholmer 
See discussion in #125 and in #118. I believe we had incorrect targets and the info in #118 should fix it. @nikhilwoodruff I believe you said this has been done. Has it been merged in yet and would it be reflected in the tax expenditure examination that @martinholmer refers to? If so, we might still have a problem so it's important to know.

**Comment by martinholmer** [comment]
I think issue #126 has been resolved by the changes to the `uprate_puf.py` code that were included in PR #144.

**Comment by donboyd5** [comment]
I agree, except that we need an issue for how to build on what's been done
in PR #144
<https://github.com/PSLmodels/tax-microdata-benchmarking/pull/144>. I'll
open it for posterity, but we won't be able to get to it in Phase 3.
