### ISSUE TITLE
CAVEAT EMPTOR: IRS targets in 2021 do not all have the same number of AGI ranges

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#141]
@nikhilwoodruff, @martinholmer 

We're not currently targeting itemized deductions by AGI range (but may end up wanting to, at least for SALT). Just a caution/reminder that the IRS published data we would use for 2021 targets by AGI range do not all have the same number of AGI ranges - it depends upon (1) which IRS spreadsheet the data come from, and (2) whether we target all filers or taxable returns only. If/when we target itemized deductions by AGI range, it will be important to make sure we handle this properly.

**Examples**

The basic AGI and income components targets we are using mostly come from 21in14ar.xls (21=2021, in=individual income, 14=IRS Table 1.4, ar=all returns). 

**For filers ("All returns"), this has 19 ranges plus a total, as shown below:**

![image](https://github.com/user-attachments/assets/68534cf6-e6b4-4159-8cbe-67af08d978c2)

**For taxpayers ("Taxable returns"), this has 15 ranges plus a total:**

![image](https://github.com/user-attachments/assets/93257d88-1600-49ba-a086-24dd5f08ce65)

The itemized deduction targets mostly come from 21in21id.xls (21=2021, in=individual income, 21=IRS Table 2.1, id=itemized deduction returns). 

**This has 22 income ranges and a total:**

![image](https://github.com/user-attachments/assets/30ef8c4b-454f-45d0-b4b4-26c0202cbb30)

There may be other variations, too.

**Comment by nikhilwoodruff** [comment]
Looked into this- I think we can say for certain it's not an issue. Although in the latest `agi_targets.csv` I have, multiple AGI ranges DO have the same `incsort` field (e.g. 1m-1.5m and 1m+ are both 16), in the cleanup script I added a while ago we map directly from the text range field (and cover all the unique fields): 
<img width="570" alt="image" src="https://github.com/user-attachments/assets/212ba82a-c760-4c3a-976f-a0bfc6af9937">

**Comment by donboyd5** [comment]
Smart. Thanks.
