### ISSUE TITLE
CTC analysis

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#145]
@nikhilwoodruff @martinholmer 

This is analysis triggered by @martinholmer's CTC tax expenditure analysis, and is foreshadowed in #127.

I have copied a lot of details below. They are taken from [this doc](https://docs.google.com/document/d/1aDwNIw8I1uPxN3NapNgk8568iqY7p4BOVE2JSzk7ymk/edit), which I may update more quickly than the details below.

My key takeaways so far are below. I will come back and amend this section as I learn more:

- As expected, values of untargeted variables go awry when we don’t have a penalty on changes in weights, but come back in line when we impose a penalty; functional form of the weight-change penalty and importance we attach to it deserve attention as 2nd-order questions. Reweighting is NOT the source of our concerns and differences - our concerns arise earlier in the data-construction process.
- We need to investigate construction of xtot and n24 in tmd -- these are construction questions, not reweighting questions:
  - why do we we have so much more xtot==1 returns and exemptions for filers (data_source==1) than either taxdata or puf2015?
  - why do we have so many more n24==2 and n24==3 returns and children for filers than either taxdata or puf2015?
- What are the CTC consequences of these differences?
- Examine the same questions for nonfilers (data_source==0)
- Examine the differences by AGI range
- TO COME: analysis of above

See details below.

**Comment by donboyd5** [comment]
**Glossary of file names**

- **taxdata** -- the 2011 puf, processed by the taxdata repo to create puf.csv, run through Tax-Calculator 2021 law using default Tax-Calculator growfactors and weights (which were based on taxdata reweighting methods); this file is based on taxdata and Tax-Calculator as of early April 2024.
- **puf2015** -- the raw 2015 puf with NO ADJUSTMENTS (includes the 4 aggregate records, does not include agedp1, agedp2, agedp3, not grown to later years, not reweighted, not run through Tax-Calculator) -- agi from this file is as reported on the raw puf (e00100). THUS, values are at 2015 levels.
- **tmd_noreweight** -- tmd_2024.csv based on issue126 commit hash 4017a0, without reweighting. Thus, this is puf2015 as adjusted by tmd (tax-microdata-benchmarking), AFTER simple growth to 2021, including per-capita growth in values and simple growth in weights, but NOT reweighting, run through Tax-Caclu
- **tmd_reweight_nopenalty** -- same as tmd_noreweight except that reweighted weights based on issue 126 targets (514 targets) are used, without any penalty for changes in weights from original weights
- **tmd_reweight_penalty**.2 -- same as tmd_reweight_nopenalty, but with a penalty for deviation from original weights - the penalty is the default penalty used in issue126, namely 0.20

**Comment by donboyd5** [comment]
**# returns and weighted sums of xtot and n24 in each file**
![image](https://github.com/user-attachments/assets/edc60d1b-aa08-41f6-9149-e8616fbe3e00)


Since this is the first table, let me explain it. The columns are n (# of unweighted records), xtot_nret (# of returns -- i.e., weighted records -- that have positive xtot), xtot_sum (weighted # exemptions on those returns); n24_nret and n24_sum have the same meanings for n24. Here’s an example -- how to read xtot_sum:

- taxdata -- the 2011 puf, grown to 2021 with taxdata weights and growfactors, run through Tax-Calculator with 2021 law, had 304 million exemptions; (NOTE: to my knowledge, xtot would not change when run through Tax-Calculator, but other variables might)
- puf2015 -- the raw 2015 puf (including aggregate records), in 2015, had 287.5 million exemptions
- tmd_noreweight -- the 2015 puf, as manipulated by tmd (tax-microdata-benchmarking), and grown to 2021 with tmd total-returns and per-return growth assumptions, but not reweighting, run through Tax-Calculator, has 317 million exemptions
- tmd_reweight_nopenalty - this reweights tmd_noreweight to hit various targets, with no penalty for how much weights can change; we now have 287 million exemptions (only coincidentally about the same as in 2015)
- tmd_reweight_penalty.2  - this reweights tmd_noreweight to hit various targets, but with a penalty importance parameter of 0.2 for how much weights can change; it has 316 million exemptions

Let’s look more closely at what happens to xtot and n24, which are not targeted, when we reweight:
Compare the progression from tmd_no_rweight to tmd_reweight_no_penalty. With no penalty, their sums change substantially (e.g., xtot sum changed from 317 million exemptions to 287 million exemptions). This is the “innocent bystander” effect of reweighting - nontargeted variables will change when we reweight, and if we have no penalty on changes in weights, the optimizer doesn’t care how much the values change.
Now compare the progression from tmd_reweight_penalty.2. When we add a penalty on changes in weights, the optimizer tries to keep weights close to their original values and so xtot_nret, xtot_sum, n24_nret, and nret_sum are all pretty close to their original values (the nret values are not as close as with no penalty, but the sums are much closer). 
Setting aside whether we used the best weight-change penalty function and whether we assigned the right amount of importance to the penalty on weight changes, this seems like an improvement, at least with respect to total number of exemptions and total number of children qualifying for child tax credit.

**Comment by donboyd5** [comment]
**# returns with exemptions by # of exemptions**
This table shows the # of returns with exemptions (not the number of exemptions), by exemption size. Remember that (1) puf2015 is at 2015 levels, and (2) all other columns are estimates of 2021 levels under 2021 law, with taxdata being based on the 2011 puf and tmd columns based on the 2015 puf. A quick comparison with the appendix tables shows that puf2015 matches what the puf2015 documentation says we should get.

![image](https://github.com/user-attachments/assets/27b59a88-1312-48ca-91ad-b95d2ab45664)

A few comments about the table above:

- taxdata values for 2021 have 10.5 million returns with 0 exemptions, but all the tmd files for 2021 have zero returns with 0 exemptions. Why? (We ignore puf2015 because it is under 2015 law.) This is under 2021 law and perhaps doesn’t matter for direct tax calculation purposes but still we should discuss because (a) perhaps it has spillover effects on other variables, and (b) a potential policy question is what happens if we re-insitute personal exemptions.
- Thus, we should discuss how we construct xtot
- tmd_reweight_nopenalty and tmd_reweight_penalty.2 do what we expect them to do -- opimtization with no weight-change penalty leads to significant differences in untargeted values but when we add a penalty these differences largely go away.
- For now, let’s focus on construction of xtot in tmd_noreweight rather than optimization.

**Comment by donboyd5** [comment]
**# of exemptions by size**
Here is the same table but showing # of exemptions rather than # of returns. The same kinds of comments arise.
![image](https://github.com/user-attachments/assets/9be0bb59-2fd5-462f-bfa7-16bab48ee681)


Looking at above, we can see that we have much greater growth in # exemptions==1 than other groups (which grow at our overall returns-population 2015 to 2021 growth rate of 6.9%). The table below shows this, and a comparison to taxdata - for xtot==1, we have 22.9% increase from the raw puf even though our overall returns-filing growth was 6.9%, and this puts us 15.5% above where taxdata is? Clearly this needs investigation.
![image](https://github.com/user-attachments/assets/90c88f26-142c-4d7f-8cd3-06f1c5941fc9)

**Comment by donboyd5** [comment]
**# returns with n24 by size**
Similar observations as before regarding what reweighting without a penalty for weight changes does to untargeted variables.
tmd_noreweight has a lot more returns with n24 than does taxdata -- perhaps a surprise given our relative results on the child tax credit calculation and the tax expenditure

![image](https://github.com/user-attachments/assets/20945c42-5a40-402c-bf28-d10957ce9caf)

**Comment by donboyd5** [comment]
**# n24 children by size of n24**

Similar observations as above.

![image](https://github.com/user-attachments/assets/87765f0d-9ba5-4fbe-b815-9d320db7ac4a)

**Comment by donboyd5** [comment]
**Appendix: IRS data**

**PUF 2015 documentation**

These tables show (1) numbers based on the full SOI sample (numbers that will be in public reports, if IRS publishes the variable in question), and (2) numbers we should expect to be able to reproduce from the raw 2015 puf IF we include the 4 aggregate records.

_Exemptions_

![image](https://github.com/user-attachments/assets/5f4dc24f-f5f4-42fc-a699-cdf2eedd0851)


_n24_
![image](https://github.com/user-attachments/assets/e9b655a5-bb68-419a-9c9b-e7cbf792c9f2)



Exemptions by AGI range in 2015 from IRS spreadsheets
![image](https://github.com/user-attachments/assets/93ac5bae-5c39-4081-8f05-9eb0c8beab51)

Exemptions over time
![image](https://github.com/user-attachments/assets/b90952b6-b118-4640-b0c1-3fe7b68e37f5)

![image](https://github.com/user-attachments/assets/4158213a-a4e1-46bd-b614-099e91051d1e)

**Comment by martinholmer** [comment]
@donboyd5,  After PR #148 is merged into the master branch, it would be interesting to see how your CTC analysis in issue #145 changes when using the master branch.

**Comment by martinholmer** [comment]
The final Phase3 tax expenditure estimates have been improved by PR #148 and PR #154, and so the CTC estimates provided here (in issue #145) are obsolete.
