### ISSUE TITLE
In create_area_weights.py temporarily should revert to assuming that CDs are based on 2010 Census (that is, 117th Congress)

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#242]
create_area_weights.py assumes that CDs are based on 2020 Census (that is, 118th Congress) but the targets data currently reflect the 117th Congress. MT had only one CD in the 117th Congress (mt-00) but 2 CDs in the 118th Congress; with the 118th assumption, the error checking code rejects mt00_targets.csv as invalid.

A simple solution is to revert to using the 117th Congress assumption and I will prepare a PR to do so.

Over the longer term, we could consider building the assumption into the targets file (e.g, a new column session with 117 or 118) so that a user could target either set of geographic boundaries.

**Comment by martinholmer** [comment]
@donboyd5 said in issue #242:
> `create_area_weights.py` assumes that CDs are based on 2020 Census (that is, 118th Congress) but the targets data currently reflect the 117th Congress.  MT had only one CD in the 117th Congress (mt-00) but 2 CDs in the 118th Congress; with the 118th assumption, the error checking code rejects `mt00_targets.csv` as invalid.

Instead of using `mt00_targets.csv` simply use `mt_targets.csv`.
