### ISSUE TITLE
Base data for tmd.csv and tmd_2021.csv are not identical, probably should put a warning on it

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#248]
tmd_2021.csv is a tmd-type file supplemented with output variables from tax-calculator, plus the pre-optimization weight. Its main use is to make it easy to compare pre- and post- weight optimization results. I may be the only user of it. It used to be identical to tmd.csv, with the only difference being the addition of new variables.

I recently discovered that tmd_2021.csv input variables no longer are identical to tmd.csv variables - there are very minor differences.

Eventually, tmd_2021.csv may no longer be useful and might be dropped from the tmd repo.

In the short term, however, I suggest putting a warning in the tmd documentation alerting potential tmd_2021.csv users to this issue.

I can do this once I resolve the permissions problem that keeps my pull requests from passing tests.

**Comment by martinholmer** [comment]
@donboyd5 said in issue #248:
> I recently discovered that `tmd_2021.csv` input variables no longer are identical to `tmd.csv` variables - there are very minor differences.

Can you be more specific about the nature of the input variable differences?

**Comment by martinholmer** [comment]
@donboyd5 said in issue #248:
> Eventually, `tmd_2021.csv` may no longer be useful and might be dropped from the tmd repo.

Is there any reason to wait?   Why not drop `tmd_2021.csv` now?

**Comment by donboyd5** [comment]
The differences are trivial but nonzero. They are primarily in the values of variables, although there can be differences in weights, too. The differences are primarily in PUF records rather than CPS records. It is not troubling from my perspective because I don't have great need for tmd_2021.csv as of now. It could become an issue if we try to retool national weight optimization sometime in the future, which is where I put tmd_2021.csv to use. There are workarounds, though (I could use tmd.csv and run it through Tax-Calculator).

The table below gives an example of differences for s006 and unweighted and weighted wages.

```
# TMDDIR is tax-microdata-benchmarking/tmd/storage/output
# tmd.csv and tmd_2021.csv.gz were created from the master branch on 10/21/2024 at about 2 pm
fpath <-  fs::path(TMDDIR, "tmd.csv.gz")
tmd <- read_csv(fpath) 

fpath <-  fs::path(TMDDIR, "tmd_2021.csv")
tmd2021 <- read_csv(fpath)

stack <- bind_rows(
  tmd |> select(RECID, data_source, s006, e00200) |> mutate(file="tmd"),
  tmd2021 |> select(RECID, data_source, s006, e00200) |> mutate(file="tmd2021")
)

stack |> 
  summarise(n_unwtd=n(), n_wtd=sum(s006), e00200_unwtd=sum(e00200), e00200_wtd=sum(e00200 * s006),
            .by=c(file, data_source)) |> 
  pivot_longer(-c(file, data_source)) |> 
  pivot_wider(names_from = file) |> 
  janitor::adorn_totals() |> 
  mutate(diff=tmd2021 - tmd,
         pdiff=diff / tmd) |> 
  gt() |> 
  fmt_number(columns = c(tmd, tmd2021, diff),
             decimals = 0) |> 
  fmt_percent(columns = pdiff,
              decimals=5)
```

![image](https://github.com/user-attachments/assets/480a3ce0-76ad-4ddf-84bd-2bd5e40bef3e)

**Comment by donboyd5** [comment]
> @donboyd5 said in issue #248:
> 
> > Eventually, `tmd_2021.csv` may no longer be useful and might be dropped from the tmd repo.
> 
> Is there any reason to wait? Why not drop `tmd_2021.csv` now?

@martinholmer Sorry, I did not see this earlier. The conservative in me says don't drop it until we take another look at national data, which may not be in Phases 4-6, but in a later phase. I'd prefer to just warn people for now, if that's ok.

**Comment by donboyd5** [comment]
Or perhaps we could just make it an undocumented feature that only you and I (and readers of this issue) know about, and then we can silently drop it after we know it's outlived its usefulness. I'm almost certain no one has used it other than me.
