### ISSUE TITLE
CD targets are missed even though optimization tolerances are met:  rounding weights to 2 decimal places is the cause

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#250]
@martinholmer I mentioned that we are missing targets, sometimes by considerable amounts, in certain cases where L-BFGS-B reports success hitting targets within tolerances.

I have tracked down the primary reason: rounding of weights to 2 decimal places.

The problem occurs, generally because we have far fewer people in a Congressional District than in the nation. Since we're using the entire data file, on average their weights are much smaller than national weights. For example, for ak00 the ratio of CD population to national population is about 0.002 giving an indication of how much smaller weights will be. Most CDs are similarly sized, so weights are smaller in other CDs, too.

That wouldn't be a problem, as long as we don't mind fractional people, if we retain all the precision.

However, when we start rounding weights to 2 decimal places, as Tax-Calculator requires, the roundoff error is a much larger percentage of the unrounded weight when weights are small than when they are large.

This isn't too much of a problem in the lower income ranges, as those records still tend to have relatively large weights. However, in the highest income ranges, weights are smallest and the roundoff error can be a very large percentage of the unrounded weight. Thus, we often find that weighted values, using the 2-decimal-place rounded weights, are 5-10% off of the targets in the highest agi range **EVEN THOUGH THE SOLVER DECLARES SUCCESS**.

The simplest (but not necessarily easiest) solution, assuming we don't mind fractional people, would be to use floating point weights in Tax-Calculator and prepare full-precision CD weights rather than rounded weights.

In any event this is something we should discuss when you're back.

The next comment provides some details.

**Comment by donboyd5** [comment]
Let me explain the problem using ak00 as an example. 

First screenshot below shows we hit targets for AGI within small tolerances for all but the highest agi range, which is off by 10.8% (taken from our [examine webpage](https://tmd-areas-examine.netlify.app/cd_results_vs_targets_tables#show-results-vs.-targets-very-preliminary)). These numbers are calculated using the weights produced by create_area_weights.py:

![image](https://github.com/user-attachments/assets/4dd362ff-9f61-4275-9e87-3cc29a884524)

The [log file](https://drive.google.com/drive/folders/1Z7ZWYTbldfuQCFbpqKi4Z8FYxkbwmhnu), however, said we didn't miss any targets:

![image](https://github.com/user-attachments/assets/eef2b972-31ae-418f-a959-09bfbca6a285)

Next screenshot shows that this happens regularly in agi stub 9 (highest agi group). (It does happen sporadically, however, in other agi ranges):

**Comment by martinholmer** [comment]
@donboyd5,  Thanks for the very helpful detective work.
