### ISSUE TITLE
Approaches to targeting selected variables

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#28]
This issue will begin a discussion of how to target selected important variables or their underlying drivers. We'll edit the list below as time goes on:

Selected important variables:

- [State and local taxes paid (#30)](https://github.com/PSLmodels/tax-microdata-benchmarking/issues/30)
- [QBID deduction](https://github.com/PSLmodels/tax-microdata-benchmarking/issues/32)
- Child (and other dependent) tax credit

Should we break each out into its own issue?

**Comment by donboyd5** [comment]
**State and local taxes**

Background: SALT deduction curtailed significantly in TCJA beginning 2018. Scheduled to return in 2026. Some estimates of cost of full return are in range of $80-100 billion annually (to be verified). Partial return (e.g., raising the cap) likely to be a significant item of debate soon.

Aggregate data on this deduction, for itemizing filers, is available in IRS spreadsheet files. However, number of itemizers and value of SALT deduction have dropped substantially post-2017. SALT deduction info for filers in the PUF is available for itemizers. This will drop off significantly when post-2017 PUFs become available.

Starting a discussion on approach:

- Try to get 2015 right:
  - Use PUF values for filers. Examine relative to IRS tables for itemizers.
  - Impute SALT values to nonfilers  - how? TBD. Could be based partly on filers relationships, but of course by definition nonfilers will be different. Can we add homeownership to our data to help with real estate taxes? Also consider tax calculations via PolicyEngine? Issues there because values will depend on state. Fortunately, SALT should be relatively unimportant for nonfilers.
  - Establish 2015 targets from IRS data and from aggregate Census State & Local Finance data
  - Reweight to hit/come near aggregate and distributional targets (requires other targets as well)
- Extrapolate to 2021 (because we have published IRS aggregates for that year)
  - growth rate for # returns from IRS and total units from (CPS?)
  - growth rates for total SALT and major components from Census S&L Finance
  - calculate per-unit growth rates
  - apply growth in units to filers and nonfilers, apply per-unit growth rates for major SALT components
  - note that this step is extrapolating state and local taxes paid, not the deduction for state and local taxes paid
  - run resulting file through Tax-Calculator to get AGI, distribution of state and local taxes paid, and deduction for state and local taxes paid
  - note that this will be dependent on other potential itemized deductions, too, because whether you can itemize will depend not just on SALT paid but also on mortgage interest paid, etc.
  - examine resulting SALT paid and SALT itemized deductions for filers relative to aggregate and distributional targets from IRS tables
  - reweight to come closer to target values, recognizing that we cannot do this well until we have reasonable targets for other major deductible items
  - Questions:
    - Can PolicyEngine calculation of SALT be helpful here?
    - How are JCT and CBO doing this?
- 2022 and later - get simple per-unit growth rates for SALT total or major components, apply them as well as growth rates for # of units

**Comment by martinholmer** [comment]
@donboyd5,  What is the status of issue #28 (which you raised in early March)?
If nothing else needs to be done, then you should close issue #30.
If something else needs to be done, please add to issue #30 an explanation of what else needs to be done.

**Comment by donboyd5** [comment]
Superceded by work we have since done. Certainly possible to make improvements and as time permits we'll return to these.

**Comment by donboyd5** [comment]
See above.
