### ISSUE TITLE
PROBLEM: PUF-PolicyEngine variables that erroneously have weighted sums = zero

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#38]
@nikhilwoodruff, and FYI @martinholmer 

**PROBLEM**: 36 variables in the 4/10/2024 PUF-PolicyEngine flat files have weighted sums of zero, suggesting that every value of these variables is zero (I have not verified that). Some of these variables are very important in tax calculations and thus this is a high priority issue.

The screenshot below shows the top 6 variables, all of which have weighted sums in the 2015 PUF of more than $100 billion. All 36 variables, ranked by weighted sums in the raw 2015 PUF 2015, are listed [here](https://pufpe-files.netlify.app/zero_weighted_sums.html). (pufpe = PUF-PolicyEngine file, tctd=Tax-Calculator / taxdata file, and puf2015 is the raw 2015 PUF as provided by SOI. See link in previous sentence for details.)

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/78f82462-1df5-4148-9e8e-c1ad687debea)

**Comment by nikhilwoodruff** [comment]
Now fixed.
