### ISSUE TITLE
Updated v7 PUF--PolicyEngine comparisons to Tax-Calculator--taxdata default, and to IRS tables

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#46]
@nikhilwoodruff @martinholmer 

I've updated the ad-hoc analyses. They can be found [here](https://pufpe-files.netlify.app/). They mostly compare the v7 PUF-PE (pufpe) 2021 file to the Tax-Calculator--taxdata (tctd) default 2021 file. There are also some comparisons to IRS published aggregates, which are more labor-intensive because they require determining proper correspondence between PUF/TC variable names and IRS spreadsheet columns and concepts; so I'll do more of those in Phase 3.

The pufpe-tctd comparisons are in [section 4](https://pufpe-files.netlify.app/compare_to_tctd.html) and the limited pufpe-tctd-irs comparisons are in [section 6](https://pufpe-files.netlify.app/compare_to_irs.html). For now, they focus on taxpayers, defined as max(c09200 - refund, 0) > 0. This is close to the IRS definition but imperfect; we'll perfect it in Phase 3. I do not believe the imperfection in defining taxpayers is a significant concern.

I do not pretend that the tctd file is the gold standard, but a lot of people have been looking at it for a lot of years, so significant differences require investigation.

In the interest of speed, I am highlighting here a few areas of concern rather than analyzing in detail. I focus on dollar amounts ($ billions) rather than percentage differences. I focus more on input variables than output variables right now.

-  pufpe AGI is much higher than tctd in the $15k-100k range; lower than tctd in the $100k-$1m range; and then higher than tctd at the high ends. I think the pufpe distribution is probably reasonable because it was targeted, but that does not mean the components of income are correct; you can see that by looking at section 6, which compares to IRS

-  pufpe AGI is $1.2 trillion higher than tctd AGI; again comparing to IRS (section 6, this seems right)

-  pufpe wages are $1.8 trillion higher than tctd, driven by the $15k-200k AGI ranges; that seems impossible to believe

-  pufpe taxable pensions and Social Security are near zero, which is not believable

-  pufpe QBID variable is zero -that must be obviously incorrect

-  pufpe medical is near zero; that can't be right

-  pufpe SALT is triple the tctd SALT

There are lots of other questions but I think for now we need to focus on the input variables.

**Comment by donboyd5** [comment]
I moved updated tables to [here](https://donboyd5.quarto.pub/pufpe-analysis/). Section 4 has aggregates for most variables in 2021, compared to taxdata for 2021.

**Comment by nikhilwoodruff** [comment]
I think we can close this issue since it's out of date- but feel free to reopen.
