### ISSUE TITLE
How to avoid GitHub test failures?

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/tax-microdata-benchmarking#56]
Related to issue #53.

**Comment by nikhilwoodruff** [comment]
@martinholmer- you'll need to file pull requests from branches on the repo rather than forks (otherwise, anyone could obtain the PUF by forking the repo). Sorry for not mentioning this- I'll add this to the README.

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #56:
> you'll need to file pull requests from branches on the repo rather than forks

Thanks for the tip, but I have no idea how to do that.   Can you provide more details?

**Comment by MaxGhenis** [comment]
As an example, you'd clone https://github.com/PSLmodels/tax-microdata-benchmarking instead of https://github.com/martinholmer/tax-microdata-benchmarking

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #56:
> As an example, you'd clone https://github.com/PSLmodels/tax-microdata-benchmarking instead of https://github.com/martinholmer/tax-microdata-benchmarking

If I can do that, what prevents anybody else from doing that, and therefore, getting access to the private PUF data?   What am I missing?

**Comment by MaxGhenis** [comment]
Only people with write access to a repo can push a PR from it without using a fork, since it involves creating a branch from the main repo (rather than a branch from one's fork).

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #56:
> Only people with write access to a repo can push a PR from it without using a fork, since it involves creating a branch from the main repo (rather than a branch from one's fork).

OK.  What steps do I need to take to get rid of https://github.com/martinholmer/tax-microdata-benchmarking and before cloning https://github.com/PSLmodels/tax-microdata-benchmarking on my computer?

**Comment by MaxGhenis** [comment]
You could do something like the reverse of this: https://stackoverflow.com/a/33817239/1840471

Or simpler could be just creating a new folder on your computer and cloning into there.

**Comment by martinholmer** [comment]
@nikhilwoodruff and @MaxGhenis,
Following Max's suggestion, I cloned this PSLmodels GitHub repository directly to my computer.  Then I created PR #75 containing a one-word change to the `README.md` file.  But the tests on GitHub still failed.  What did I do wrong?

**Comment by martinholmer** [comment]
Worked after TOKEN was undated on GitHub.
@MaxGhenis and @nikhilwoodruff,  Thanks for the help on this.
