### ISSUE TITLE
Extend basic flat file with more variables

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/tax-microdata-benchmarking#6]
We have Tax-Calculator working, but only with earnings. We should extend with the rest of the variable list needed for most tax reform analysis.

**Comment by nikhilwoodruff** [comment]
There's 68 variables in the taxcalc CPS data file, so before going through individual ones, here's potentially a data-driven approach: as a quick first pass, can we say "important == high non-zero percentage"? Here's a histogram of non-zero percentages in the CPS data file columns:

<img width="723" alt="image" src="https://github.com/PSLmodels/tax-microdata-benchmarking/assets/35577657/7226ebcc-26d0-471f-8af3-fe1a8405a189">

**Comment by nikhilwoodruff** [comment]
Looking at this, I'm going to start from the far right side and work left, occasionally checking the taxcalc income tax estimates- perhaps if we start getting income tax aggregates close to with the full CPS file but with like 70% of the variables or something, we can pause early and see where we are.

**Comment by nikhilwoodruff** [comment]
Actually I'm going to add in the order as in `tax_unit.py` in taxdata [here](https://github.dev/pslmodels/taxdata) since that also has the implementation details to make sure I'm matching that.

**Comment by donboyd5** [comment]
> Looking at this, I'm going to start from the far right side and work left, occasionally checking the taxcalc income tax estimates- perhaps if we start getting income tax aggregates close to with the full CPS file but with like 70% of the variables or something, we can pause early and see where we are. I'm not anticipating any big issues in particular with translating the variable values into PolicyEngine's file, but in 68 variables I am expecting some kind of unexpected bug or issue at some point.

Wouldn't a high non-zero percentage imply working from left to right? I must be misinterpreting what you say, @nikhilwoodruff. I think that's a fine first principle, but we also need variables that relatively few people have nonzero values for -- capital gains would be one -- that have large impacts on liability; and variables that relatively few people have that have large policy significance -- e.g., (potential) SALT deduction.

**Comment by nikhilwoodruff** [comment]
Now complete
