### ISSUE TITLE
Why doing PolicyEngine-US labor-supply response?

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/tax-microdata-benchmarking#77]
When running `tax-microdata` tests, I get the following warning from `policyengine-us`.
Why are we doing labor supply response when we are just creating data?
```
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-ackages/policyengine_us/
      variables/gov/simulation/labor_supply_response/labor_supply_response.py:284:
RuntimeWarning: invalid value encountered in divide
    earnings > 0, employment_income / earnings, 1
```

**Comment by MaxGhenis** [comment]
Related https://github.com/PolicyEngine/policyengine-us/issues/4515

**Comment by nikhilwoodruff** [comment]
To clarify, no actual labor supply response simulations are taking place- the labor supply response is zero but we're still apportioning it among filers, which is causing a warning we should avoid.
