### ISSUE TITLE
Data examination results for pension contributions

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/tax-microdata-benchmarking#82]
The amount of defined-contribution (DC) pension contributions (`pencon_p` for the tax unit head and `pencon_s` for the tax unit spouse when married filing jointly) seems too low, primarily because very few people in our most recent dataset have a positive value for these two variables.

Here is a tabulation of the `tmd.csv` file (for 2021) that is being used to generate the most recent [examination results](https://github.com/PSLmodels/tax-microdata-benchmarking/blob/master/tax_microdata_benchmarking/examination/results3.md):

```
% awk -F, 'NR==1{for(i=1;i<=NF;i++)print i,$i}' tmd.csv | grep -e pencon -e s006
11 s006
50 pencon_p
51 pencon_s

% awk -F, 'NR==1{next}{t++}$50>0{n++}END{print t,n,n/t}' tmd.csv 
233412   6789   0.0290859                 <--- UNWEIGHTED HEADS (#)

% awk -F, 'NR==1{next}{w=$11;t+=w}$50>0{n+=w}END{print t*1e-6,n*1e-6,n/t}' tmd.csv
219.594   15.171   0.0690865              <--- WEIGHTED HEADS (#M)

% awk -F, 'NR==1{next}{w=$11;t+=w}$50>0{n+=w}$51>0{n+=w}END{print t*1e-6,n*1e-6,n/t}' tmd.csv
219.594   16.0148   0.0729291             <--- WEIGHTED PEOPLE (#M)

% awk -F, 'NR==1{next}{w=$11;t+=w;c+=w*($50+$51)}END{print t*1e-6,c*1e-9}' tmd.csv
219.594   48.7986                         <--- WEIGHTED DOLLAR CONTRIBUTONS ($B)
```

The 16.0 million people with positive DC contributions compares with [USDOL Form 5500 results](https://www.dol.gov/sites/dolgov/files/EBSA/researchers/statistics/retirement-bulletins/private-pension-plan-bulletins-abstract-2020.pdf#page=7) for 2020 "active participants" of nearly 85.3 million:

<img width="964" alt="Screenshot 2024-05-11 at 4 36 50 PM" src="https://github.com/PSLmodels/tax-microdata-benchmarking/assets/12170745/3cd216c5-db5d-49dc-9129-c269c79c2e4b">

.

And the $48.8 billion tabulation compares with the USDOL Form 5500 results for 2020 of almost $586 billion shown above.  So, we have less than ten percent of DC pension contributions.  Even if the DOL contribution total includes both employee and employer DC contributions, the employee DC contribution amounts in the `tmd.csv` file seem too low.

**Comment by martinholmer** [comment]
Better targets for years up through 2018 are from [IRS-SOI tabulations of W-2 forms](https://www.irs.gov/statistics/soi-tax-stats-individual-information-return-form-w2-statistics).

The 2018 tabulations of taxpayers with an **employee** pension contributions are:
```
Number of taxpayers (#M)               60.353
Gross (Medicare) earnings ($B)       5062.371
Employee pension contributions ($B)   332.520
```

So, the 16.0 million taxpayers in 2021 tabulated using the `tmd.csv` file is clearly too low.
Also, the $48.8 billion in 2021 employee pension contributions tabulated using the `tmd.csv` file is way below the actual 2018 value of almost $333 billion.

It does appear that @donboyd5 was correct to highlight this issue in #8.

The 2011 IRS-SOI W-2 tabulations were used in the taxdata repository's [`inpute_pencon.py` module](https://github.com/PSLmodels/taxdata/blob/master/taxdata/puf/impute_pencon.py) to impute `pencon_p` and `pencon_s` values to 2011 PUF data.   The 2015 IRS-SOI tabulations could be used to impute more accurate pension contributions to the 2015 PUF.

**Comment by donboyd5** [comment]
This is extremely helpful. Thanks.

**Comment by martinholmer** [comment]
After the merge of PR #90, the weighted sum of the `pencon_p` and `pencon_s` variables is much larger.   So, the original issue (that pension contributions were way too low) has now been resolved.
