### ISSUE TITLE
Aggregate records are included in the tmd output files

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#97]
@nikhilwoodruff could you please remove the 4 aggregate records from the various tmd files (the analysis below is based on tmd_2021.csv), and think about the potential issues noted below? Thanks. FYI, @martinholmer.

Here is what the 2015 PUF documentation (p.3) says about aggregate records:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/26b5bc6b-2149-4558-a301-3b2cd3bb117d)

I had raised concerns about the importance of these records - capital gains, in particular, are disproportionately large on one of these records – and said that I think we should explore in the future whether there is information in these 4 records that we can use. However, for purposes of the current project we agreed - as other modelers using previous PUFs had done - that the proper and conservative approach for now is to exclude these records from our tmd files. We can revisit in the future whether there are ways we can use information from these records to improve upon our simple rule of excluding them.

However, these 4 records nonetheless appear to be in our tmd files. The table below shows, for tmd_2021.csv:

- RECID for the 4 aggregate records
- tmd values in 2021 for s006 (our final weight), c00100 (AGI, calculated), c01000 (net capital gains, calculated), and taxbc (tax before credits), each with _tmd suffix,
- weighted values for the tmd c00100 and c01000 variables, with wtd_ prefix (weighted by s006_tmd)
- raw puf values in 2015 for e00100 (AGI) and e00100 (net capital gains), with _puf sufix
- I do not show original puf weights or pre-optimization tmd weights because the changes were not significant enough to be concerning.

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/0bc1fd1b-aa37-4534-bed7-d1bbc34fbe9c)

A few observations:

- First and foremost, we don’t want the 4 aggregate records in our output file and should remove them.
- The extraordinary nature of these records is worth remembering: for example, RECID 999999 has average AGI of $369.3 million, and weighted capital gains are $111 billion (out of about $2 trillion).
- That certainly means these 4 records will have thrown off our optimized reweighting significantly and it will be important to see how things change after we remove them.
- Strange things have happened to these records as we moved from the raw 2015 puf to the extrapolated (uprated), reweighted tmd file for 2021. For example, raw 2015 AGI (e00100) on RECID 999996 changed from -$96.4 million to calculated AGI in 2021 of $11.1 million. That may be just fine - it may be Tax-Calculator doing what it should be doing. We don’t have to worry about it for these records but we do need to ask ourselves whether it suggests anything strange is going on that we should worry about for the other 225k records we have. I don’t have anything particular I’m worried about, it’s just an observation that I think we need to think about.

Seems like it would be a good idea to have a test for whether aggregate records are in the output files.

**Comment by nikhilwoodruff** [comment]
OK yes- will remove and add a test asserting the RECIDs are not in the output files.
