### ISSUE TITLE
Large changes in national weights from original values likely an important issue

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#99]
As we've discussed, at present the tax-microdata-benchmarking optimization approach does not penalize changes in weights, and simply seeks to minimize differences in weighted sums from IRS-based target values, using 2021 values. This means any changes in weights are acceptable to the program.

The tables below compare values based on s006 (the optimized weight) to values based on s006_original (the immediately prior weight).

The first table shows quantiles of the ratio of s006 to s006_original. One record increased 9 thousand fold in importance, and 10% of records almost doubled or more in importance.  Ignore the negative ratios - that should not happen once #98 is addressed.

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/d201e721-dd55-4ccd-8310-614ee0f66fbb)

How much is too much? I don't know. By comparison, last I knew, taxdata tried to restrict weight changes to be within about 50%; it might be higher or lower now, but probably not by much. A 9,000-fold increase in importance seems like too much to me. As we've discussed many times, it all comes down to whether you think there is information in existing weights beyond the role they play in hitting targeted values. I think there is - I think there are almost certainly relationships across variables that are correlated with weights and some of those relationships, when aggregated, will be very wrong if we just let weights be anything as long as they help a file hit selected targeted variables. It is the untargeted variables I worry about.

I haven't tried to verify this analytically. Eventually, I or we may. But until then, the conservative approach, and the one we need to take, is to include a penalty for changes in weights in our optimization function.

A few more tables:

Changes in weight (s006 - s006_original).

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/df6987fa-7453-46f9-bbdc-456de7ace2a7)

Top 20 records by ratio of new to old weight:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/94a57425-1d73-4377-b161-e7411d820da0)

dweight, dagi, and dtaxbc are the changes in weighted values of those variables. Thus, reweighting of record number 7 increased the weight by 4,316 (becoming 439 times as important as before), resulting in an aggregate reduction of  almost $8 billion of AGI, albeit no change in tax before credits.

Top 20 records by absolute value of change in aggregate taxbc:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/6be66420-0fdb-48a4-99bb-abbd0d92bb39)

Six records that increase aggregate taxbc by $100 million or more. We can ignore the first, I guess, as that should be dropped from the dataset (see issue #97).

Finally, note that s006 and s006_original are not as close as we'd expect, suggesting that the growth factor used to calculate 2006_original from the PUF 2015 s006, of about 6.9% I believe, is too low.

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/580497eb-dc80-4efa-a0ba-418eae05bc8a)

**Comment by martinholmer** [comment]
@donboyd5, PR #148 shows that some of the large weight changes in the reweighting process were caused by the inclusion of "taxable return" statistics in the reweighting loss function.   Perhaps you should revisit this issue after PR #148 is merged.   It would be interesting to know if some of the large weight changes are gone after the merge of PR #148.

**Comment by donboyd5** [comment]
The taxable returns issue, previously identified by @martinholmer, was resolved by eliminating targets for taxable returns.

The question of large changes in weights, more generally, will be resolved if and when we apply the L-BFGS-B method with regularization, currently used for areas, to the national data, as discussed in issue [#195](https://github.com/PSLmodels/tax-microdata-benchmarking/issues/195).
